version: '3.4'

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

services:
  api-service:
    build:
      context: .
      args:
        ASPNET_VERSION: ${ASPNET_VERSION}
        SDK_VERSION: ${SDK_VERSION}
        WORKDIR: ${WORKDIR}
      dockerfile: ./Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: dotnet
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=${HTTPS_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${HTTPS_ASPNET_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${HTTPS_ASPNET_VOLUME_PATH}:/https/aspnetapp.pfx:rw
    env_file: .env
    restart: always